### ISSUE TITLE
Why check in node_modules.tar.gz and bower_components?

### ISSUE THREAD

**Issue by JohnnyEstilles** [pinoyyid/ngGAPI#1]
I was wondering why you check in the required Node modules (in `node_modules.tar.gz`) and Bower components (in `bower_components/**`). First, it's not a widely used/accepted practice, it unnecessarily bloats your repo, and finally some Node modules may need to be reinstalled anyway, depending on the OS development environment.

Why not instead define all required dependencies in `package.json` and `bower.json`, then use ask contributing developers/testers install dependencies using:

```
npm install
bower install
````

This is just a suggestion, in an attempt to make your project more "contributor friendly", especially across multiple OS development environments.

**Comment by pinoyyid** [comment]
Thanks for the suggestion and pointers. The simple answer is ignorance on my part, never having wrangled npm or bower before now.
The project is still in kinda 'bootsrap' mode, so I haven't yet thought about packaging. I'll look at restructuring the dependencies over the next few days.

**Comment by JohnnyEstilles** [comment]
@pinoyyid, I will gladly submit it a PR. I wasn't really thinking about packaging either. I'm sure that will come down the road. Should PRs be submitted against master? I have a few more suggestions if your open to them.

**Comment by pinoyyid** [comment]
Very much open to PR's and suggestions. I've just checked in a bunch of enhancements to the low level HttPService. If you could submit PR's against 'dev' that would be ideal.

**Comment by JohnnyEstilles** [comment]
Thanks for the update. I will submit a PR within the next day or so. I will also open some additional issues to address a few other concerns.

**Comment by JohnnyEstilles** [comment]
Submitted PR #4 to address this issue

**Comment by pinoyyid** [comment]
fixed by PR #4
