### ISSUE TITLE
Quick Start Link in README.md broken

### ISSUE THREAD

**Issue by yankustefan** [pinoyyid/ngGAPI#6]
Hi pinoyyid

Thanks for sharing your work!

Just a detail:
The link in README.md at "Quick Start" is broken:
https://github.com/pinoyyid/ngGAPI/blob/nggapi_lib/nggapi_dist.zip?raw=true

However I can download the files individually which is fine.

**Comment by pinoyyid** [comment]
fixed by cb1045a60f9a9ecf99eb3a6c3bcba04137380483
