### ISSUE TITLE
promise based oauth

### ISSUE THREAD

**Issue by yankustefan** [pinoyyid/ngGAPI#8]
Just a thought:

Currently, OauthService.getAccessToken() returns either the key or something like "!RETRY=500".

Would it make sense to offer a "accessCheck" function to that returns a promise?
- reject if no permission
- resolve with access token?

That would be great if:
- I want to pass the token to somewhere else, but have to wait for it
- use with router-ui, so I can restrict access to certain views if there is no permission

**Comment by JohnnyEstilles** [comment]
@yankustefan I think the premise behind the current implementation is to mimic, as much as possible, Google's auth API. I understand that we will adding helper methods, to serve as syntactic sugar. This may be a use-case for one.

(@pinoyyid, please correct me if I'm of base, and deserve a kick in the head ... :-)

**Comment by pinoyyid** [comment]
I think we've got your use case covered. getAccessToken() is designed to be called by the HttpService within the context of a DriveService request. So the error response !RETRY=500 is intended to be consumed and acted upon by the HttpService on behalf of your app, so you never need to worry about it. Internally, OauthService will automatically attempt a background auth/refresh if there is no current access token. 

That is meant to deal with the majority of cases.

For any use case that isn't covered, the Oauth configuration provides two advanced settings:-

// Configure what a request should do if there is no access token
//    ms=0: The request will fail and return an error to the application to deal with
//    ms>0: The request will be retried 10 times with a delay of ms milliseconds. The default is ms=500
OauthServiceProvider.setNoAccessTokenPolicy(1000);                 
// provide your own function to return an access token. 
// myFunction should return a string which will be set into the Authorization Bearer header 
OauthServiceProvider.setGetAccessTokenFunction: function (myFunction)

By setting setNoAccessTokenPolicy(0), the no-access-token condition will return to your app, and you can then wrap that return in your own promise.

Having said that, I think the suggestion of `accessCheck()` is a good one, provided I can find a way to wrangle gapi.auth to play nicely. We're constrained by what the low level Google lib will and won't do for us.

**Comment by pinoyyid** [comment]
Note to self. I suspect simply having refreshToken return a promise, resolved or rejected as appropriate, will provide this feature.

**Comment by pinoyyid** [comment]
The more I think about it, the more I agree that getAccessToken retuning a promise cleans up a lot of internal code as well as providing more functionality to the app, eg. by providing a notify('refreshing token') which the app can act on. My initial concern was that giving a promise to a newbie might be confusing, but on reflection, newbies are unlikely to be calling getAccessToken themselves anyway.

**Comment by pinoyyid** [comment]
This has been implemented in the at_promise branch. `OuthService,getAccessToken():IPromise<Google GapiAccessTokenObject>`. Will be merged to master in this week.

**Comment by yankustefan** [comment]
Hi, I tried the updated nggapi_base.min.js and nggapi_drive.min.js and tested with minimal.html.

I get the following error:
'''
TypeError: Cannot read property 'getToken' of undefined
    at a.getAccessToken (nggapi_base.min.js:1)
    at a._doHttp (nggapi_base.min.js:1)
    at a.dq (nggapi_base.min.js:1)
    at nggapi_base.min.js:1
    at angular.min.js:114
    at n.$get.n.$eval (angular.min.js:126)
    at n.$get.n.$digest (angular.min.js:123)
    at n.$get.n.$apply (angular.min.js:126)
    at angular.min.js:90angular.min.js:102 (anonymous function)angular.min.js:76 $getangular.min.js:114 (anonymous function)angular.min.js:126 $get.n.$evalangular.min.js:123 $get.n.$digestangular.min.js:126 $get.n.$applyangular.min.js:90 (anonymous function)
'''

**Comment by pinoyyid** [comment]
it looks like the .min.js files weren't rebuilt. I've rebuilt (grunt distlib) and pushed the changes to the at_promise branch
